# SPDX-FileCopyrightText: 2026 Ralfs K. Vētra
#
# SPDX-License-Identifier: MIT

SOC_CUR_DIR  := ./soc/stm8s
ABSTRACT_DIR := $(SOC_CUR_DIR)/abstract

SRCS_C += \
	$(SOC_CUR_DIR)/soc.c \
	$(SOC_CUR_DIR)/vector.c

SRCS_S += $(SOC_CUR_DIR)/crt0.s

LDSCRIPT += $(SOC_CUR_DIR)/soc.lkf
