# SPDX-FileCopyrightText: 2026 Ralfs K. Vētra
#
# SPDX-License-Identifier: MIT

FLASH_DIR  := $(DRIVERS_DIR)/flash
SERIAL_DIR := $(DRIVERS_DIR)/serial

SRCS_C += \
	$(SERIAL_DIR)/uart_stm8.c \
	$(FLASH_DIR)/flash_stm8.c
