# SPDX-FileCopyrightText: 2026 Ralfs K. Vētra
#
# SPDX-License-Identifier: MIT

DRV_CUR_DIR := ./drivers
FLASH_DIR   := $(DRV_CUR_DIR)/flash
SERIAL_DIR  := $(DRV_CUR_DIR)/serial

SRCS_C += \
	$(SERIAL_DIR)/uart_stm8.c \
	$(FLASH_DIR)/flash_stm8.c
